# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Ui/H10CMainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_H10CMainWindow(object):
    def setupUi(self, H10CMainWindow):
        H10CMainWindow.setObjectName(_fromUtf8("H10CMainWindow"))
        H10CMainWindow.resize(860, 585)
        self.centralwidget = QtGui.QWidget(H10CMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabLive = QtGui.QWidget()
        self.tabLive.setEnabled(True)
        self.tabLive.setObjectName(_fromUtf8("tabLive"))
        self.tabWidget.addTab(self.tabLive, _fromUtf8(""))
        self.tabExperiments = QtGui.QWidget()
        self.tabExperiments.setObjectName(_fromUtf8("tabExperiments"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabExperiments)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grbExp = QtGui.QGroupBox(self.tabExperiments)
        self.grbExp.setObjectName(_fromUtf8("grbExp"))
        self.gridLayout = QtGui.QGridLayout(self.grbExp)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.grbExp)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.lvidexp = QtGui.QListView(self.grbExp)
        self.lvidexp.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lvidexp.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lvidexp.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lvidexp.setWordWrap(True)
        self.lvidexp.setObjectName(_fromUtf8("lvidexp"))
        self.verticalLayout.addWidget(self.lvidexp)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.grbExp)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.pbtnAddVideoExp = QtGui.QPushButton(self.grbExp)
        self.pbtnAddVideoExp.setObjectName(_fromUtf8("pbtnAddVideoExp"))
        self.horizontalLayout.addWidget(self.pbtnAddVideoExp)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tbStartVideo = QtGui.QToolButton(self.grbExp)
        self.tbStartVideo.setMinimumSize(QtCore.QSize(64, 64))
        self.tbStartVideo.setIconSize(QtCore.QSize(64, 64))
        self.tbStartVideo.setAutoRaise(False)
        self.tbStartVideo.setObjectName(_fromUtf8("tbStartVideo"))
        self.verticalLayout_2.addWidget(self.tbStartVideo)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.grbExp, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabExperiments, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.tabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        H10CMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(H10CMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName(_fromUtf8("menu_About"))
        H10CMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(H10CMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        H10CMainWindow.setStatusBar(self.statusbar)
        self.actionE_xit = QtGui.QAction(H10CMainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.actionLicence = QtGui.QAction(H10CMainWindow)
        self.actionLicence.setObjectName(_fromUtf8("actionLicence"))
        self.action_About = QtGui.QAction(H10CMainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_How_to = QtGui.QAction(H10CMainWindow)
        self.action_How_to.setObjectName(_fromUtf8("action_How_to"))
        self.menu_File.addAction(self.actionLicence)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menu_About.addAction(self.action_About)
        self.menu_About.addAction(self.action_How_to)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(H10CMainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(H10CMainWindow)

    def retranslateUi(self, H10CMainWindow):
        H10CMainWindow.setWindowTitle(_translate("H10CMainWindow", "Gaitech H10C Device", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLive), _translate("H10CMainWindow", "Live Data Monitor", None))
        self.grbExp.setTitle(_translate("H10CMainWindow", "Perform Experiments", None))
        self.label_2.setText(_translate("H10CMainWindow", "Video Experiments", None))
        self.lvidexp.setToolTip(_translate("H10CMainWindow", "Select video experiment to perform", None))
        self.label.setText(_translate("H10CMainWindow", "Add experiment", None))
        self.pbtnAddVideoExp.setToolTip(_translate("H10CMainWindow", "Open new video experiment", None))
        self.pbtnAddVideoExp.setText(_translate("H10CMainWindow", "Open", None))
        self.tbStartVideo.setToolTip(_translate("H10CMainWindow", "Start Video Experiment", None))
        self.tbStartVideo.setText(_translate("H10CMainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExperiments), _translate("H10CMainWindow", "Experiments", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("H10CMainWindow", "Device Configuration", None))
        self.menu_File.setTitle(_translate("H10CMainWindow", "&File", None))
        self.menu_About.setTitle(_translate("H10CMainWindow", "&Help", None))
        self.actionE_xit.setText(_translate("H10CMainWindow", "E&xit", None))
        self.actionLicence.setText(_translate("H10CMainWindow", "Modify Licence", None))
        self.action_About.setText(_translate("H10CMainWindow", "&About Gaitech", None))
        self.action_How_to.setText(_translate("H10CMainWindow", "&How to ... ?", None))

