# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Ui/H10CSettings.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_H10CSettings(object):
    def setupUi(self, H10CSettings):
        H10CSettings.setObjectName(_fromUtf8("H10CSettings"))
        H10CSettings.resize(867, 477)
        self.formLayout = QtGui.QFormLayout(H10CSettings)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gbNearbyDevices = QtGui.QGroupBox(H10CSettings)
        self.gbNearbyDevices.setObjectName(_fromUtf8("gbNearbyDevices"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbNearbyDevices)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ldevView = QtGui.QListView(self.gbNearbyDevices)
        self.ldevView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ldevView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.ldevView.setAlternatingRowColors(True)
        self.ldevView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.ldevView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.ldevView.setObjectName(_fromUtf8("ldevView"))
        self.verticalLayout.addWidget(self.ldevView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnLKey = QtGui.QPushButton(self.gbNearbyDevices)
        self.btnLKey.setObjectName(_fromUtf8("btnLKey"))
        self.horizontalLayout.addWidget(self.btnLKey)
        self.btnScan = QtGui.QToolButton(self.gbNearbyDevices)
        self.btnScan.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnScan.setObjectName(_fromUtf8("btnScan"))
        self.horizontalLayout.addWidget(self.btnScan)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.gbNearbyDevices)
        self.gbActiveDevices = QtGui.QGroupBox(H10CSettings)
        self.gbActiveDevices.setObjectName(_fromUtf8("gbActiveDevices"))
        self.gridLayout = QtGui.QGridLayout(self.gbActiveDevices)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnConnDiscon = QtGui.QPushButton(self.gbActiveDevices)
        self.btnConnDiscon.setObjectName(_fromUtf8("btnConnDiscon"))
        self.gridLayout.addWidget(self.btnConnDiscon, 0, 2, 1, 1)
        self.cmbRefMode = QtGui.QComboBox(self.gbActiveDevices)
        self.cmbRefMode.setObjectName(_fromUtf8("cmbRefMode"))
        self.cmbRefMode.addItem(_fromUtf8(""))
        self.cmbRefMode.addItem(_fromUtf8(""))
        self.cmbRefMode.addItem(_fromUtf8(""))
        self.cmbRefMode.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbRefMode, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.gbActiveDevices)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.cmbDevName = QtGui.QComboBox(self.gbActiveDevices)
        self.cmbDevName.setObjectName(_fromUtf8("cmbDevName"))
        self.gridLayout.addWidget(self.cmbDevName, 0, 1, 1, 1)
        self.lblSigLoss = QtGui.QLabel(self.gbActiveDevices)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSigLoss.setFont(font)
        self.lblSigLoss.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSigLoss.setObjectName(_fromUtf8("lblSigLoss"))
        self.gridLayout.addWidget(self.lblSigLoss, 2, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gbActiveDevices)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.gbActiveDevices)
        self.gbROS = QtGui.QGroupBox(H10CSettings)
        self.gbROS.setCheckable(True)
        self.gbROS.setChecked(False)
        self.gbROS.setObjectName(_fromUtf8("gbROS"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbROS)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbNode = QtGui.QComboBox(self.gbROS)
        self.cmbNode.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cmbNode.setObjectName(_fromUtf8("cmbNode"))
        self.gridLayout_2.addWidget(self.cmbNode, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gbROS)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.btnNode = QtGui.QToolButton(self.gbROS)
        self.btnNode.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnNode.setObjectName(_fromUtf8("btnNode"))
        self.gridLayout_2.addWidget(self.btnNode, 0, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.gbROS)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.graphicsView = QtGui.QGraphicsView(H10CSettings)
        self.graphicsView.setMinimumSize(QtCore.QSize(480, 0))
        self.graphicsView.setMaximumSize(QtCore.QSize(640, 16777215))
        self.graphicsView.setStyleSheet(_fromUtf8("background: transparent"))
        self.graphicsView.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsView.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.gbFiltering = QtGui.QGroupBox(H10CSettings)
        self.gbFiltering.setObjectName(_fromUtf8("gbFiltering"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbFiltering)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.gbFiltering)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.dspinHigh = QtGui.QDoubleSpinBox(self.gbFiltering)
        self.dspinHigh.setObjectName(_fromUtf8("dspinHigh"))
        self.gridLayout_3.addWidget(self.dspinHigh, 0, 1, 1, 1)
        self.dspinLow = QtGui.QDoubleSpinBox(self.gbFiltering)
        self.dspinLow.setMaximum(250.0)
        self.dspinLow.setObjectName(_fromUtf8("dspinLow"))
        self.gridLayout_3.addWidget(self.dspinLow, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gbFiltering)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.dspinNHigh = QtGui.QDoubleSpinBox(self.gbFiltering)
        self.dspinNHigh.setMaximum(250.0)
        self.dspinNHigh.setObjectName(_fromUtf8("dspinNHigh"))
        self.gridLayout_3.addWidget(self.dspinNHigh, 1, 3, 1, 1)
        self.dspinNLow = QtGui.QDoubleSpinBox(self.gbFiltering)
        self.dspinNLow.setObjectName(_fromUtf8("dspinNLow"))
        self.gridLayout_3.addWidget(self.dspinNLow, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gbFiltering)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 2, 1, 1)
        self.btnboxFilter = QtGui.QDialogButtonBox(self.gbFiltering)
        self.btnboxFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnboxFilter.setObjectName(_fromUtf8("btnboxFilter"))
        self.gridLayout_3.addWidget(self.btnboxFilter, 2, 0, 1, 4, QtCore.Qt.AlignRight)
        self.label_5 = QtGui.QLabel(self.gbFiltering)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.gbFiltering)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)

        self.retranslateUi(H10CSettings)
        QtCore.QMetaObject.connectSlotsByName(H10CSettings)

    def retranslateUi(self, H10CSettings):
        H10CSettings.setWindowTitle(_translate("H10CSettings", "Avertus H10C Device Settings", None))
        self.gbNearbyDevices.setTitle(_translate("H10CSettings", "Nearby Avertus Devices", None))
        self.btnLKey.setToolTip(_translate("H10CSettings", "View and modify Licence Keys", None))
        self.btnLKey.setText(_translate("H10CSettings", "Update Licence Key", None))
        self.btnScan.setToolTip(_translate("H10CSettings", "Search nearby for Avertus H10C Headsets", None))
        self.btnScan.setText(_translate("H10CSettings", "Scan", None))
        self.gbActiveDevices.setTitle(_translate("H10CSettings", "Active Device", None))
        self.btnConnDiscon.setText(_translate("H10CSettings", "Connect", None))
        self.cmbRefMode.setToolTip(_translate("H10CSettings", "Select Reference Mode", None))
        self.cmbRefMode.setItemText(0, _translate("H10CSettings", "Common Referencing", None))
        self.cmbRefMode.setItemText(1, _translate("H10CSettings", "Average Referencing", None))
        self.cmbRefMode.setItemText(2, _translate("H10CSettings", "Longitudinal-Bipolar", None))
        self.cmbRefMode.setItemText(3, _translate("H10CSettings", "Transverse-Bipolar", None))
        self.label_2.setText(_translate("H10CSettings", "Reference Mode", None))
        self.lblSigLoss.setToolTip(_translate("H10CSettings", "<html><head/><body><p>Data loss (last 2 minutes, overall connection)</p></body></html>", None))
        self.lblSigLoss.setText(_translate("H10CSettings", "0 %", None))
        self.label_8.setText(_translate("H10CSettings", "Signal Loss", None))
        self.gbROS.setToolTip(_translate("H10CSettings", "Check to enabling modification of URI and Node", None))
        self.gbROS.setTitle(_translate("H10CSettings", "ROS", None))
        self.cmbNode.setToolTip(_translate("H10CSettings", "Select gaitech_bci node", None))
        self.label_3.setText(_translate("H10CSettings", "Device Node", None))
        self.btnNode.setToolTip(_translate("H10CSettings", "Refresh Nodes", None))
        self.btnNode.setText(_translate("H10CSettings", "R", None))
        self.gbFiltering.setTitle(_translate("H10CSettings", "Filtering", None))
        self.label_4.setText(_translate("H10CSettings", "High Pass", None))
        self.label_6.setText(_translate("H10CSettings", "Notch Low", None))
        self.label_7.setText(_translate("H10CSettings", "Notch High", None))
        self.label_5.setText(_translate("H10CSettings", "Low Pass", None))

